version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "type:dependencies"
      - "priority:low"
    commit-message:
      prefix: "deps(composer):"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "type:dependencies"
      - "priority:low"
    commit-message:
      prefix: "deps(npm):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "type:dependencies"
      - "priority:low"
    commit-message:
      prefix: "deps(actions):"

